# this customization changes the one of the host paths to a
# writable volume on bottlerocket
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/

# change the name to distinguish it from base
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: efs-csi-node-bottlerocket
  target:
    kind: DaemonSet
    name: "efs-csi-node"

# change the efs-utils-config to a writable volume on bottlerocket
patchesStrategicMerge:
- |-
  kind: DaemonSet
  apiVersion: apps/v1
  metadata:
    name: efs-csi-node
    namespace: kube-system
  spec:
    template:
      spec:
        volumes:
          - name: efs-utils-config
            hostPath:
              path: /var/amazon/efs
              type: DirectoryOrCreate

# change the name to distinguish it from base
- |-
  kind: DaemonSet
  apiVersion: apps/v1
  metadata:
    name: efs-csi-node
    namespace: kube-system
  spec:
    selector:
      matchLabels:
        app: efs-csi-node-bottlerocket
    template:
      metadata:
        labels:
          app: efs-csi-node-bottlerocket
