# this customization changes the one of the host paths to a
# writable volume on bottlerocket
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../../base

patchesStrategicMerge:
# change the efs-utils-config to a writable volume on bottlerocket
- efs-utils-config.yaml
# change names to distinguish them from base
- selector-names.yaml
